### ISSUE TITLE
Suggest: README with link to pre-print and browser

### ISSUE THREAD

**Issue by richelbilderbeek** [pgxcentre/ExPheWAS#1]
ExPheWas seems awesome to me!

The GitHub, however, feels less helpful than it could.

I suggest to add a README with links to the pre-print (and accepted manuscript in the future) and browser, such as the text below. That would help me and others to find the other parts.

Sure I can make a Pull Request to the `dev` branch if asked :-)

Cheers, Richel

# ExPheWas

ExPheWas is [what it is] and can be found at [https://exphewas.statgen.org](https://exphewas.statgen.org).

## Citation

Legault, Marc-André, Louis-Philippe Lemieux Perreault, and Marie-Pierre Dubé. "ExPheWas: a browser for gene-based pheWAS associations." medRxiv (2021).

Manuscript can be found [here](https://www.medrxiv.org/content/10.1101/2021.03.17.21253824v1)

**Comment by legaultmarc** [comment]
Thanks a lot for your interest and suggestion! I added a README on dev, it will be merged into master tomorrow.
